Added lua
pinpt/dialect pull request #1
Opened 2017-01-14 21:09 UTC by Robindiddams

I added lua comment parsing and a popular unit testing framework "busted", along with tests for both

2017-01-15 00:43 UTC, jhaynie requested changes
i think you have some issues with `busted` that need to be resolved.

2017-01-15 00:43 UTC, jhaynie commented on pkg/lua/lua.go
> +	"github.com/pinpt/dialect/pkg/lua/busted"
busted? is this old?

2017-01-15 00:43 UTC, jhaynie commented on pkg/lua/busted/busted.go
> +}
i think these was left over from javascript

2017-01-15 00:44 UTC, jhaynie commented on pkg/lua/lua.go
> +}
is this old?

2017-01-16 19:51 UTC, Robindiddams commented on pkg/lua/busted/busted.go
> +}
busted uses the same syntax as mocha, so I used the same code from mocha. or am I missing your question?

2017-01-24 01:53 UTC, jhaynie commented on pkg/lua/busted/busted.go
> +}
oh so busted is the name of a lua testing package? oops. i thought it was some weird name of your pkg. 👍

2017-01-24 01:54 UTC, merged